Department.create(name: "Amazonas", ubigeo: "01")
Department.create(name: "Ancash", ubigeo: "02")
Department.create(name: "Apurimac", ubigeo: "03")
Department.create(name: "Arequipa", ubigeo: "04")
Department.create(name: "Ayacucho", ubigeo: "05")
Department.create(name: "Cajamarca", ubigeo: "06")
Department.create(name: "Callao", ubigeo: "07")
Department.create(name: "Cusco", ubigeo: "08")
Department.create(name: "Huancavelica", ubigeo: "09")
Department.create(name: "Huanuco", ubigeo: "10")
Department.create(name: "Ica", ubigeo: "11")
Department.create(name: "Junin", ubigeo: "12")
Department.create(name: "La Libertad", ubigeo: "13")
Department.create(name: "Lambayeque", ubigeo: "14")
Department.create(name: "Lima", ubigeo: "15")
Department.create(name: "Loreto", ubigeo: "16")
Department.create(name: "Madre de Dios", ubigeo: "17")
Department.create(name: "Moquegua", ubigeo: "18")
Department.create(name: "Pasco", ubigeo: "19")
Department.create(name: "Piura", ubigeo: "20")
Department.create(name: "Puno", ubigeo: "21")
Department.create(name: "San Martin", ubigeo: "22")
Department.create(name: "Tacna", ubigeo: "23")
Department.create(name: "Tumbes", ubigeo: "24")
Department.create(name: "Ucayali", ubigeo: "25")

puts "8_UbigeoDepartment_seeds done at: " + Time.new.to_s
