Province.create(name: "Chachapoyas", ubigeo: "0101", department_id: 1)
Province.create(name: "Bagua", ubigeo: "0102", department_id: 1)
Province.create(name: "Bongara", ubigeo: "0103", department_id: 1)
Province.create(name: "Condorcanqui", ubigeo: "0104", department_id: 1)
Province.create(name: "Luya", ubigeo: "0105", department_id: 1)
Province.create(name: "Rodriguez de Mendoza", ubigeo: "0106", department_id: 1)
Province.create(name: "Utcubamba", ubigeo: "0107", department_id: 1)
Province.create(name: "Huaraz", ubigeo: "0201", department_id: 2)
Province.create(name: "Aija", ubigeo: "0202", department_id: 2)
Province.create(name: "Antonio Raymondi", ubigeo: "0203", department_id: 2)
Province.create(name: "Asuncion", ubigeo: "0204", department_id: 2)
Province.create(name: "Bolognesi", ubigeo: "0205", department_id: 2)
Province.create(name: "Carhuaz", ubigeo: "0206", department_id: 2)
Province.create(name: "Carlos Fermin Fitzcarrald", ubigeo: "0207", department_id: 2)
Province.create(name: "Casma", ubigeo: "0208", department_id: 2)
Province.create(name: "Corongo", ubigeo: "0209", department_id: 2)
Province.create(name: "Huari", ubigeo: "0210", department_id: 2)
Province.create(name: "Huarmey", ubigeo: "0211", department_id: 2)
Province.create(name: "Huaylas", ubigeo: "0212", department_id: 2)
Province.create(name: "Mariscal Luzuriaga", ubigeo: "0213", department_id: 2)
Province.create(name: "Ocros", ubigeo: "0214", department_id: 2)
Province.create(name: "Pallasca", ubigeo: "0215", department_id: 2)
Province.create(name: "Pomabamba", ubigeo: "0216", department_id: 2)
Province.create(name: "Recuay", ubigeo: "0217", department_id: 2)
Province.create(name: "Santa", ubigeo: "0218", department_id: 2)
Province.create(name: "Sihuas", ubigeo: "0219", department_id: 2)
Province.create(name: "Yungay", ubigeo: "0220", department_id: 2)
Province.create(name: "Abancay", ubigeo: "0301", department_id: 3)
Province.create(name: "Andahuaylas", ubigeo: "0302", department_id: 3)
Province.create(name: "Antabamba", ubigeo: "0303", department_id: 3)
Province.create(name: "Aymaraes", ubigeo: "0304", department_id: 3)
Province.create(name: "Cotabambas", ubigeo: "0305", department_id: 3)
Province.create(name: "Chincheros", ubigeo: "0306", department_id: 3)
Province.create(name: "Grau", ubigeo: "0307", department_id: 3)
Province.create(name: "Arequipa", ubigeo: "0401", department_id: 4)
Province.create(name: "Camana", ubigeo: "0402", department_id: 4)
Province.create(name: "Caraveli", ubigeo: "0403", department_id: 4)
Province.create(name: "Castilla", ubigeo: "0404", department_id: 4)
Province.create(name: "Caylloma", ubigeo: "0405", department_id: 4)
Province.create(name: "Condesuyos", ubigeo: "0406", department_id: 4)
Province.create(name: "Islay", ubigeo: "0407", department_id: 4)
Province.create(name: "La Uniòn", ubigeo: "0408", department_id: 4)
Province.create(name: "Huamanga", ubigeo: "0501", department_id: 5)
Province.create(name: "Cangallo", ubigeo: "0502", department_id: 5)
Province.create(name: "Huanca Sancos", ubigeo: "0503", department_id: 5)
Province.create(name: "Huanta", ubigeo: "0504", department_id: 5)
Province.create(name: "La Mar", ubigeo: "0505", department_id: 5)
Province.create(name: "Lucanas", ubigeo: "0506", department_id: 5)
Province.create(name: "Parinacochas", ubigeo: "0507", department_id: 5)
Province.create(name: "Pàucar del Sara Sara", ubigeo: "0508", department_id: 5)
Province.create(name: "Sucre", ubigeo: "0509", department_id: 5)
Province.create(name: "Victor Fajardo", ubigeo: "0510", department_id: 5)
Province.create(name: "Vilcas Huaman", ubigeo: "0511", department_id: 5)
Province.create(name: "Cajamarca", ubigeo: "0601", department_id: 6)
Province.create(name: "Cajabamba", ubigeo: "0602", department_id: 6)
Province.create(name: "Celendin", ubigeo: "0603", department_id: 6)
Province.create(name: "Chota", ubigeo: "0604", department_id: 6)
Province.create(name: "Contumaza", ubigeo: "0605", department_id: 6)
Province.create(name: "Cutervo", ubigeo: "0606", department_id: 6)
Province.create(name: "Hualgayoc", ubigeo: "0607", department_id: 6)
Province.create(name: "Jaen", ubigeo: "0608", department_id: 6)
Province.create(name: "San Ignacio", ubigeo: "0609", department_id: 6)
Province.create(name: "San Marcos", ubigeo: "0610", department_id: 6)
Province.create(name: "San Miguel", ubigeo: "0611", department_id: 6)
Province.create(name: "San Pablo", ubigeo: "0612", department_id: 6)
Province.create(name: "Santa Cruz", ubigeo: "0613", department_id: 6)
Province.create(name: "Prov. Const. del Callao", ubigeo: "0701", department_id: 7)
Province.create(name: "Cusco", ubigeo: "0801", department_id: 8)
Province.create(name: "Acomayo", ubigeo: "0802", department_id: 8)
Province.create(name: "Anta", ubigeo: "0803", department_id: 8)
Province.create(name: "Calca", ubigeo: "0804", department_id: 8)
Province.create(name: "Canas", ubigeo: "0805", department_id: 8)
Province.create(name: "Canchis", ubigeo: "0806", department_id: 8)
Province.create(name: "Chumbivilcas", ubigeo: "0807", department_id: 8)
Province.create(name: "Espinar", ubigeo: "0808", department_id: 8)
Province.create(name: "La Convencion", ubigeo: "0809", department_id: 8)
Province.create(name: "Paruro", ubigeo: "0810", department_id: 8)
Province.create(name: "Paucartambo", ubigeo: "0811", department_id: 8)
Province.create(name: "Quispicanchi", ubigeo: "0812", department_id: 8)
Province.create(name: "Urubamba", ubigeo: "0813", department_id: 8)
Province.create(name: "Huancavelica", ubigeo: "0901", department_id: 9)
Province.create(name: "Acobamba", ubigeo: "0902", department_id: 9)
Province.create(name: "Angaraes", ubigeo: "0903", department_id: 9)
Province.create(name: "Castrovirreyna", ubigeo: "0904", department_id: 9)
Province.create(name: "Churcampa", ubigeo: "0905", department_id: 9)
Province.create(name: "Huaytara", ubigeo: "0906", department_id: 9)
Province.create(name: "Tayacaja", ubigeo: "0907", department_id: 9)
Province.create(name: "Huanuco", ubigeo: "1001", department_id: 10)
Province.create(name: "Ambo", ubigeo: "1002", department_id: 10)
Province.create(name: "Dos de Mayo", ubigeo: "1003", department_id: 10)
Province.create(name: "Huacaybamba", ubigeo: "1004", department_id: 10)
Province.create(name: "Huamalies", ubigeo: "1005", department_id: 10)
Province.create(name: "Leoncio Prado", ubigeo: "1006", department_id: 10)
Province.create(name: "Marañon", ubigeo: "1007", department_id: 10)
Province.create(name: "Pachitea", ubigeo: "1008", department_id: 10)
Province.create(name: "Puerto Inca", ubigeo: "1009", department_id: 10)
Province.create(name: "Lauricocha ", ubigeo: "1010", department_id: 10)
Province.create(name: "Yarowilca ", ubigeo: "1011", department_id: 10)
Province.create(name: "Ica ", ubigeo: "1101", department_id: 11)
Province.create(name: "Chincha ", ubigeo: "1102", department_id: 11)
Province.create(name: "Nasca ", ubigeo: "1103", department_id: 11)
Province.create(name: "Palpa ", ubigeo: "1104", department_id: 11)
Province.create(name: "Pisco ", ubigeo: "1105", department_id: 11)
Province.create(name: "Huancayo ", ubigeo: "1201", department_id: 12)
Province.create(name: "Concepcion ", ubigeo: "1202", department_id: 12)
Province.create(name: "Chanchamayo ", ubigeo: "1203", department_id: 12)
Province.create(name: "Jauja ", ubigeo: "1204", department_id: 12)
Province.create(name: "Junin ", ubigeo: "1205", department_id: 12)
Province.create(name: "Satipo ", ubigeo: "1206", department_id: 12)
Province.create(name: "Tarma ", ubigeo: "1207", department_id: 12)
Province.create(name: "Yauli ", ubigeo: "1208", department_id: 12)
Province.create(name: "Chupaca ", ubigeo: "1209", department_id: 12)
Province.create(name: "Trujillo ", ubigeo: "1301", department_id: 13)
Province.create(name: "Ascope ", ubigeo: "1302", department_id: 13)
Province.create(name: "Bolivar ", ubigeo: "1303", department_id: 13)
Province.create(name: "Chepen ", ubigeo: "1304", department_id: 13)
Province.create(name: "Julcan ", ubigeo: "1305", department_id: 13)
Province.create(name: "Otuzco ", ubigeo: "1306", department_id: 13)
Province.create(name: "Pacasmayo ", ubigeo: "1307", department_id: 13)
Province.create(name: "Pataz ", ubigeo: "1308", department_id: 13)
Province.create(name: "Sanchez Carrion ", ubigeo: "1309", department_id: 13)
Province.create(name: "Santiago de Chuco ", ubigeo: "1310", department_id: 13)
Province.create(name: "Gran Chimu ", ubigeo: "1311", department_id: 13)
Province.create(name: "Viru ", ubigeo: "1312", department_id: 13)
Province.create(name: "Chiclayo ", ubigeo: "1401", department_id: 14)
Province.create(name: "Ferreñafe ", ubigeo: "1402", department_id: 14)
Province.create(name: "Lambayeque ", ubigeo: "1403", department_id: 14)
Province.create(name: "Lima ", ubigeo: "1501", department_id: 15)
Province.create(name: "Barranca ", ubigeo: "1502", department_id: 15)
Province.create(name: "Cajatambo ", ubigeo: "1503", department_id: 15)
Province.create(name: "Canta ", ubigeo: "1504", department_id: 15)
Province.create(name: "Cañete ", ubigeo: "1505", department_id: 15)
Province.create(name: "Huaral ", ubigeo: "1506", department_id: 15)
Province.create(name: "Huarochiri ", ubigeo: "1507", department_id: 15)
Province.create(name: "Huaura ", ubigeo: "1508", department_id: 15)
Province.create(name: "Oyon ", ubigeo: "1509", department_id: 15)
Province.create(name: "Yauyos ", ubigeo: "1510", department_id: 15)
Province.create(name: "Maynas ", ubigeo: "1601", department_id: 16)
Province.create(name: "Alto Amazonas ", ubigeo: "1602", department_id: 16)
Province.create(name: "Loreto ", ubigeo: "1603", department_id: 16)
Province.create(name: "Mariscal Ramon Castilla ", ubigeo: "1604", department_id: 16)
Province.create(name: "Requena ", ubigeo: "1605", department_id: 16)
Province.create(name: "Ucayali ", ubigeo: "1606", department_id: 16)
Province.create(name: "Datem del Marañon ", ubigeo: "1607", department_id: 16)
Province.create(name: "Putumayo", ubigeo: "1608", department_id: 16)
Province.create(name: "Tambopata ", ubigeo: "1701", department_id: 17)
Province.create(name: "Manu ", ubigeo: "1702", department_id: 17)
Province.create(name: "Tahuamanu ", ubigeo: "1703", department_id: 17)
Province.create(name: "Mariscal Nieto ", ubigeo: "1801", department_id: 18)
Province.create(name: "General Sanchez Cerro ", ubigeo: "1802", department_id: 18)
Province.create(name: "Ilo ", ubigeo: "1803", department_id: 18)
Province.create(name: "Pasco ", ubigeo: "1901", department_id: 19)
Province.create(name: "Daniel Alcides Carrion ", ubigeo: "1902", department_id: 19)
Province.create(name: "Oxapampa ", ubigeo: "1903", department_id: 19)
Province.create(name: "Piura ", ubigeo: "2001", department_id: 20)
Province.create(name: "Ayabaca ", ubigeo: "2002", department_id: 20)
Province.create(name: "Huancabamba ", ubigeo: "2003", department_id: 20)
Province.create(name: "Morropon ", ubigeo: "2004", department_id: 20)
Province.create(name: "Paita ", ubigeo: "2005", department_id: 20)
Province.create(name: "Sullana ", ubigeo: "2006", department_id: 20)
Province.create(name: "Talara ", ubigeo: "2007", department_id: 20)
Province.create(name: "Sechura ", ubigeo: "2008", department_id: 20)
Province.create(name: "Puno ", ubigeo: "2101", department_id: 21)
Province.create(name: "Azangaro ", ubigeo: "2102", department_id: 21)
Province.create(name: "Carabaya ", ubigeo: "2103", department_id: 21)
Province.create(name: "Chucuito ", ubigeo: "2104", department_id: 21)
Province.create(name: "El Collao ", ubigeo: "2105", department_id: 21)
Province.create(name: "Huancane ", ubigeo: "2106", department_id: 21)
Province.create(name: "Lampa ", ubigeo: "2107", department_id: 21)
Province.create(name: "Melgar ", ubigeo: "2108", department_id: 21)
Province.create(name: "Moho ", ubigeo: "2109", department_id: 21)
Province.create(name: "San Antonio de Putina ", ubigeo: "2110", department_id: 21)
Province.create(name: "San Roman ", ubigeo: "2111", department_id: 21)
Province.create(name: "Sandia ", ubigeo: "2112", department_id: 21)
Province.create(name: "Yunguyo ", ubigeo: "2113", department_id: 21)
Province.create(name: "Moyobamba ", ubigeo: "2201", department_id: 22)
Province.create(name: "Bellavista ", ubigeo: "2202", department_id: 22)
Province.create(name: "El Dorado ", ubigeo: "2203", department_id: 22)
Province.create(name: "Huallaga ", ubigeo: "2204", department_id: 22)
Province.create(name: "Lamas ", ubigeo: "2205", department_id: 22)
Province.create(name: "Mariscal Caceres ", ubigeo: "2206", department_id: 22)
Province.create(name: "Picota ", ubigeo: "2207", department_id: 22)
Province.create(name: "Rioja ", ubigeo: "2208", department_id: 22)
Province.create(name: "San Martin ", ubigeo: "2209", department_id: 22)
Province.create(name: "Tocache ", ubigeo: "2210", department_id: 22)
Province.create(name: "Tacna ", ubigeo: "2301", department_id: 23)
Province.create(name: "Candarave ", ubigeo: "2302", department_id: 23)
Province.create(name: "Jorge Basadre ", ubigeo: "2303", department_id: 23)
Province.create(name: "Tarata ", ubigeo: "2304", department_id: 23)
Province.create(name: "Tumbes ", ubigeo: "2401", department_id: 24)
Province.create(name: "Contralmirante Villar ", ubigeo: "2402", department_id: 24)
Province.create(name: "Zarumilla ", ubigeo: "2403", department_id: 24)
Province.create(name: "Coronel Portillo ", ubigeo: "2501", department_id: 25)
Province.create(name: "Atalaya ", ubigeo: "2502", department_id: 25)
Province.create(name: "Padre Abad ", ubigeo: "2503", department_id: 25)
Province.create(name: "Purus", ubigeo: "2504", department_id: 25)

puts "9_UbigeoProvince_seeds done at: " + Time.new.to_s
