LocationOwner.create([{ name: 'Absolute Games SA', business_name: 'Absolute Games SA', document_number: '20545188202' }])
LocationOwner.create([{ name: 'Administradora Jockey Plaza Shopping Center S.A.', business_name: 'Administradora Jockey Plaza Shopping Center S.A.', document_number: '20306841506' }])
LocationOwner.create([{ name: 'Administradora y Gestora de Inmuebles SAC', business_name: 'Administradora y Gestora de Inmuebles SAC', document_number: '20506943991' }])
LocationOwner.create([{ name: 'Aeropuertos Andinos del Perú S.A.', business_name: 'Aeropuertos Andinos del Perú S.A.', document_number: '20538593053' }])
LocationOwner.create([{ name: 'Aeropuertos del Perú SA', business_name: 'Aeropuertos del Perú SA', document_number: '20514513172' }])
LocationOwner.create([{ name: 'Agroindustrias San Jacinto SAA', business_name: 'Agroindustrias San Jacinto SAA', document_number: '20116225779' }])
LocationOwner.create([{ name: 'Ajeper S.A', business_name: 'Ajeper S.A', document_number: '20331061655' }])
LocationOwner.create([{ name: 'ALPAMAYO INVERSIONES SAC', business_name: 'ALPAMAYO INVERSIONES SAC', document_number: '20530811183' }])
LocationOwner.create([{ name: 'Altek Trading SAC', business_name: 'Altek Trading SAC', document_number: '20345681460' }])
LocationOwner.create([{ name: 'Alvis Monta�ez Bas�lides', business_name: 'Alvis Monta�ez Bas�lides', document_number: '10292389391' }])
LocationOwner.create([{ name: 'Am�rica Express SA', business_name: 'Am�rica Express SA', document_number: '20114111342' }])
LocationOwner.create([{ name: 'Am�rica Salud SAC', business_name: 'Am�rica Salud SAC', document_number: '20506046751' }])
LocationOwner.create([{ name: 'Andean odyssey SCRL', business_name: 'Andean odyssey SCRL', document_number: '20518406311' }])
LocationOwner.create([{ name: 'Andean Slots SAC', business_name: 'Andean Slots SAC', document_number: '20296532917' }])
LocationOwner.create([{ name: 'Andina de Salud SA', business_name: 'Andina de Salud SA', document_number: '20313463631' }])
LocationOwner.create([{ name: 'Ang�lica Violeta D�az Estela', business_name: 'Ang�lica Violeta D�az Estela', document_number: '10063647727' }])
LocationOwner.create([{ name: 'Arte Per� SCRL', business_name: 'Arte Per� SCRL', document_number: '20526917376' }])
LocationOwner.create([{ name: 'Artesan�as Urin Huanca SA', business_name: 'Artesan�as Urin Huanca SA', document_number: '20108110075' }])
LocationOwner.create([{ name: 'ASEME SA', business_name: 'ASEME SA', document_number: '20261303362' }])
LocationOwner.create([{ name: 'Asociación Centro Artesanal Cusco', business_name: 'Asociación Centro Artesanal Cusco', document_number: '20485310321' }])
LocationOwner.create([{ name: 'Asociación de Artesanos Inka Plaza', business_name: 'Asociación de Artesanos Inka Plaza', document_number: '20575704011' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes Artesanos Servicios y Afines del Centro Ferial Se�or de Luren', business_name: 'Asociación de Comerciantes Artesanos Servicios y Afines del Centro Ferial Se�or de Luren', document_number: '20471597920' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes Campo Ferial Tupac Amaru KM. 11 Comas - ACCAFTA', business_name: 'Asociación de Comerciantes Campo Ferial Tupac Amaru KM. 11 Comas - ACCAFTA', document_number: '20207188621' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes del Centro Comercial Bellavista', business_name: 'Asociación de Comerciantes del Centro Comercial Bellavista', document_number: '20158029872' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes del Centro Comercial El Molino I', business_name: 'Asociación de Comerciantes del Centro Comercial El Molino I', document_number: '20527128405' }])
LocationOwner.create([{ name: 'ASOCIACION DE COMERCIANTES DEL CENTRO COMERCIAL LOS PINOS', business_name: 'ASOCIACION DE COMERCIANTES DEL CENTRO COMERCIAL LOS PINOS', document_number: '20506702951' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes El Ed�n de Monterrico', business_name: 'Asociación de Comerciantes El Ed�n de Monterrico', document_number: '20507475061' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes Las Fronteras Unidas de Grau', business_name: 'Asociación de Comerciantes Las Fronteras Unidas de Grau', document_number: '20458462454' }])
LocationOwner.create([{ name: 'Asociación de Comerciantes Unificados de los Campos Feriales de Villa El Salvador', business_name: 'Asociación de Comerciantes Unificados de los Campos Feriales de Villa El Salvador', document_number: '20502914562' }])
LocationOwner.create([{ name: 'Asociación de Peque�os Comerciantes Polvos Rosados', business_name: 'Asociación de Peque�os Comerciantes Polvos Rosados', document_number: '20123053975' }])
LocationOwner.create([{ name: 'Asociación de Propietarios Centro Comercial Importadores de los 5 Continentes', business_name: 'Asociación de Propietarios Centro Comercial Importadores de los 5 Continentes', document_number: '20504414826' }])
LocationOwner.create([{ name: 'Asociación de Propietarios de la Galer�a Mesa Redonda', business_name: 'Asociación de Propietarios de la Galer�a Mesa Redonda', document_number: '20505150521' }])
LocationOwner.create([{ name: 'Asociación de Propietarios del Centro Comercial Polvos Azules', business_name: 'Asociación de Propietarios del Centro Comercial Polvos Azules', document_number: '20375536898' }])
LocationOwner.create([{ name: 'Asociación de Propietarios del Mercado Bol�var', business_name: 'Asociación de Propietarios del Mercado Bol�var', document_number: '20113296918' }])
LocationOwner.create([{ name: 'Asociación de Propietarios del Mercado Virgen de las Mercedes ', business_name: 'Asociación de Propietarios del Mercado Virgen de las Mercedes ', document_number: '20258325584' }])
LocationOwner.create([{ name: 'Asociación Deportiva Los Inkas Golf Club', business_name: 'Asociación Deportiva Los Inkas Golf Club', document_number: '20101149421' }])
LocationOwner.create([{ name: 'Asociación Galer�a Comercial Coronel Mendoza', business_name: 'Asociación Galer�a Comercial Coronel Mendoza', document_number: '20119290792' }])
LocationOwner.create([{ name: 'Asociación Junta de Propietarios de la Galer�a Ferial La Cachina', business_name: 'Asociación Junta de Propietarios de la Galer�a Ferial La Cachina', document_number: '20511470731' }])
LocationOwner.create([{ name: 'Asociación Peruano Japonesa', business_name: 'Asociación Peruano Japonesa', document_number: '20101267467' }])
LocationOwner.create([{ name: 'Astrid Caballa Torres', business_name: 'Astrid Caballa Torres', document_number: '10404516294' }])
LocationOwner.create([{ name: 'Aventura Plaza SA', business_name: 'Aventura Plaza SA', document_number: '20513669560' }])
LocationOwner.create([{ name: 'Banco Internacional del Perú SAA - INTERBANK', business_name: 'Banco Internacional del Perú SAA - INTERBANK', document_number: '20100053455' }])
LocationOwner.create([{ name: 'BANCO PICHINCHA S.A.A.', business_name: 'BANCO PICHINCHA S.A.A.', document_number: '20100105862' }])
LocationOwner.create([{ name: 'Botica Farma Claudia SAC', business_name: 'Botica Farma Claudia SAC', document_number: '20494389402' }])
LocationOwner.create([{ name: 'Caja Municipal de Ahorro y Cr�dito de Huancayo', business_name: 'Caja Municipal de Ahorro y Cr�dito de Huancayo', document_number: '20130200789' }])
LocationOwner.create([{ name: 'Caja Municipal de Ahorro y Cr�dito de Trujillo', business_name: 'Caja Municipal de Ahorro y Cr�dito de Trujillo', document_number: '20132243230' }])
LocationOwner.create([{ name: 'Caja Municipal de Ahorro y Cr�dito Ica SA', business_name: 'Caja Municipal de Ahorro y Cr�dito Ica SA', document_number: '20104888934' }])
LocationOwner.create([{ name: 'Caja Municipal de Ahorro y Cr�dito Maynas S.A.', business_name: 'Caja Municipal de Ahorro y Cr�dito Maynas S.A.', document_number: '20103845328' }])
LocationOwner.create([{ name: 'Caja Municipal de Ahorro y Cr�dito Tacna', business_name: 'Caja Municipal de Ahorro y Cr�dito Tacna', document_number: '20130098488' }])
LocationOwner.create([{ name: 'Candy Market Campoy SRL', business_name: 'Candy Market Campoy SRL', document_number: '20263809441' }])
LocationOwner.create([{ name: 'Cartavio Sociedad An�nima Abierta', business_name: 'Cartavio Sociedad An�nima Abierta', document_number: '20131867744' }])
LocationOwner.create([{ name: 'Casa Grande Sociedad An�nima Abierta', business_name: 'Casa Grande Sociedad An�nima Abierta', document_number: '20131823020' }])
LocationOwner.create([{ name: 'Catalina Roxana Castro Salda�a ', business_name: 'Catalina Roxana Castro Salda�a ', document_number: '10079981058' }])
LocationOwner.create([{ name: 'Centauro Grifos SRL', business_name: 'Centauro Grifos SRL', document_number: '20171910987' }])
LocationOwner.create([{ name: 'Centro Comercial Los Delfines', business_name: 'Centro Comercial Los Delfines', document_number: '20519325285' }])
LocationOwner.create([{ name: 'Centro Comercial Plaza', business_name: 'Centro Comercial Plaza', document_number: '20447722560' }])
LocationOwner.create([{ name: 'Centro Comercial Plaza Jesús María SAC', business_name: 'Centro Comercial Plaza Jesús María SAC', document_number: '20508920696' }])
LocationOwner.create([{ name: 'Centro Internacional de la Papa', business_name: 'Centro Internacional de la Papa', document_number: '20142582725' }])
LocationOwner.create([{ name: 'Centro Naval del Perú Sede San Borja', business_name: 'Centro Naval del Perú Sede San Borja', document_number: '20502707770' }])
LocationOwner.create([{ name: 'Centros Comerciales del Perú SA', business_name: 'Centros Comerciales del Perú SA', document_number: '20294751565' }])
LocationOwner.create([{ name: 'Centros de Salud Peruanos SAC', business_name: 'Centros de Salud Peruanos SAC', document_number: '20602393934' }])
LocationOwner.create([{ name: 'Ch�vez Vite Rosa Elvira', business_name: 'Ch�vez Vite Rosa Elvira', document_number: '10038674558' }])
LocationOwner.create([{ name: 'Chowdhury Mohiuddin Al Mamun', business_name: 'Chowdhury Mohiuddin Al Mamun', document_number: '15546210780' }])
LocationOwner.create([{ name: 'C�a. de Seguridad Prosegur S.A.', business_name: 'C�a. de Seguridad Prosegur S.A.', document_number: '20100148162' }])
LocationOwner.create([{ name: 'Cineplex SA', business_name: 'Cineplex SA', document_number: '20429683581' }])
LocationOwner.create([{ name: 'Claudia Reyes Ch�vez', business_name: 'Claudia Reyes Ch�vez', document_number: '10178976091' }])
LocationOwner.create([{ name: 'Cl�nica San Pablo SAC', business_name: 'Cl�nica San Pablo SAC', document_number: '20107463705' }])
LocationOwner.create([{ name: 'CLUB DE REGATAS LIMA', business_name: 'CLUB DE REGATAS LIMA', document_number: '20136907400' }])
LocationOwner.create([{ name: 'Club Internacional Arequipa', business_name: 'Club Internacional Arequipa', document_number: '20168420014' }])
LocationOwner.create([{ name: 'Comercial Francis EIRL', business_name: 'Comercial Francis EIRL', document_number: '20440665994' }])
LocationOwner.create([{ name: 'Comercial Turismo Tacna SA', business_name: 'Comercial Turismo Tacna SA', document_number: '20501150542' }])
LocationOwner.create([{ name: 'Complejo Agroindustrial Beta S.A.', business_name: 'Complejo Agroindustrial Beta S.A.', document_number: '20297939131' }])
LocationOwner.create([{ name: 'COMPLEJO COMERCIAL Y RESIDENCIAL UNICACHI S.A.', business_name: 'COMPLEJO COMERCIAL Y RESIDENCIAL UNICACHI S.A.', document_number: '20504868428' }])
LocationOwner.create([{ name: 'Congreso de la Rep�blica', business_name: 'Congreso de la Rep�blica', document_number: '20161749126' }])
LocationOwner.create([{ name: 'Consorcio de Inversiones Santa F� ', business_name: 'Consorcio de Inversiones Santa F� ', document_number: '20255081650' }])
LocationOwner.create([{ name: 'Cooperativa de Ahorro y Cr�dito Ilo Ltda', business_name: 'Cooperativa de Ahorro y Cr�dito Ilo Ltda', document_number: '20136284593' }])
LocationOwner.create([{ name: 'Cooperativa de Ahorro y Cr�dito San Crist�bal de Huamanga', business_name: 'Cooperativa de Ahorro y Cr�dito San Crist�bal de Huamanga', document_number: '20129175975' }])
LocationOwner.create([{ name: 'Cooperativa de Ahorro y Cr�dito Santa Mar�a Magdalena Ltda', business_name: 'Cooperativa de Ahorro y Cr�dito Santa Mar�a Magdalena Ltda', document_number: '20129258323' }])
LocationOwner.create([{ name: 'Cooperativa de Servicios Especiales Mercado Central Ltda.', business_name: 'Cooperativa de Servicios Especiales Mercado Central Ltda.', document_number: '20122093981' }])
LocationOwner.create([{ name: 'Cooperativa de Servicios Especiales Mercado Ciudad de Dios Ltda', business_name: 'Cooperativa de Servicios Especiales Mercado Ciudad de Dios Ltda', document_number: '12457898652' }])
LocationOwner.create([{ name: 'Cooperativa de Servicios Especiales San Francisco LTDA', business_name: 'Cooperativa de Servicios Especiales San Francisco LTDA', document_number: '20156720217' }])
LocationOwner.create([{ name: 'Cooperativa del Centro Comercial Se�or de Luren', business_name: 'Cooperativa del Centro Comercial Se�or de Luren', document_number: '20106132306' }])
LocationOwner.create([{ name: 'C�rpac SA', business_name: 'C�rpac SA', document_number: '20100004675' }])
LocationOwner.create([{ name: 'Corporaci�n 5 de Noviembre', business_name: 'Corporaci�n 5 de Noviembre', document_number: '20117639445' }])
LocationOwner.create([{ name: 'Corporaci�n de Inversiones ILO S.A.C', business_name: 'Corporaci�n de Inversiones ILO S.A.C', document_number: '20601274516' }])
LocationOwner.create([{ name: 'Corporaci�n Hotelera Metor SA', business_name: 'Corporaci�n Hotelera Metor SA', document_number: '20386303003' }])
LocationOwner.create([{ name: 'Corporaci�n Lumar SAC', business_name: 'Corporaci�n Lumar SAC', document_number: '20515885332' }])
LocationOwner.create([{ name: 'Corporaci�n Okey SAC', business_name: 'Corporaci�n Okey SAC', document_number: '20506170762' }])
LocationOwner.create([{ name: 'Corporacion primax S.A.', business_name: 'Corporacion primax S.A.', document_number: '20554545743' }])
LocationOwner.create([{ name: 'Corporaci�n Tur�stica Peruana SAC', business_name: 'Corporaci�n Tur�stica Peruana SAC', document_number: '20265815830' }])
LocationOwner.create([{ name: 'Corporaci�n Vega SAC', business_name: 'Corporaci�n Vega SAC', document_number: '20502257987' }])
LocationOwner.create([{ name: 'Costa de Sol S.A.', business_name: 'Costa de Sol S.A.', document_number: '20231843460' }])
LocationOwner.create([{ name: 'Cubica Gestora Inmobiliaria SAC', business_name: 'Cubica Gestora Inmobiliaria SAC', document_number: '20522094715' }])
LocationOwner.create([{ name: 'Delgado Loayza Yeni', business_name: 'Delgado Loayza Yeni', document_number: '10239984156' }])
LocationOwner.create([{ name: 'Delia Paucar Blanco', business_name: 'Delia Paucar Blanco', document_number: '10239496526' }])
LocationOwner.create([{ name: 'DIGITAL HOSTELS SAC', business_name: 'DIGITAL HOSTELS SAC', document_number: '20603417756' }])
LocationOwner.create([{ name: 'Diners Club Per� SA', business_name: 'Diners Club Per� SA', document_number: '20100118760' }])
LocationOwner.create([{ name: 'Distribuidora Vania SRL', business_name: 'Distribuidora Vania SRL', document_number: '20481349801' }])
LocationOwner.create([{ name: 'Diveimport SA', business_name: 'Diveimport SA', document_number: '20502797230' }])
LocationOwner.create([{ name: 'Doa Holding SAC', business_name: 'Doa Holding SAC', document_number: '20509588849' }])
LocationOwner.create([{ name: 'Donaciano P�ucar Inca', business_name: 'Donaciano P�ucar Inca', document_number: '10069835771' }])
LocationOwner.create([{ name: 'Doris Per� Tours E.I.R.L.', business_name: 'Doris Per� Tours E.I.R.L.', document_number: '10167755807' }])
LocationOwner.create([{ name: 'E y G Per� SAC', business_name: 'E y G Per� SAC', document_number: '20514599620' }])
LocationOwner.create([{ name: 'E. Wong S.A.', business_name: 'E. Wong S.A.', document_number: '20100106915' }])
LocationOwner.create([{ name: 'E/S Ada Peregrina G�lvez Troncos', business_name: 'E/S Ada Peregrina G�lvez Troncos', document_number: '10067550230' }])
LocationOwner.create([{ name: 'Eckerd Per� S.A.', business_name: 'Eckerd Per� S.A.', document_number: '20331066703' }])
LocationOwner.create([{ name: 'EGASA PERU SAC', business_name: 'EGASA PERU SAC', document_number: '20546406688' }])
LocationOwner.create([{ name: 'El Portal 195 S.A.C.', business_name: 'El Portal 195 S.A.C.', document_number: '20600877870' }])
LocationOwner.create([{ name: 'Elmerson Cipriani Tello', business_name: 'Elmerson Cipriani Tello', document_number: '10402691200' }])
LocationOwner.create([{ name: 'Empresa de Transporte Tur�stico Olano SA', business_name: 'Empresa de Transporte Tur�stico Olano SA', document_number: '20135414931' }])
LocationOwner.create([{ name: 'Empresa de Transportes Ave F�nix SAC', business_name: 'Empresa de Transportes Ave F�nix SAC', document_number: '20133605291' }])
LocationOwner.create([{ name: 'Empresa Municipal Santiago de Surco S.A. EMUSSA', business_name: 'Empresa Municipal Santiago de Surco S.A. EMUSSA', document_number: '20502733851' }])
LocationOwner.create([{ name: 'Empresa Regional de Servicio de Electricidad del Oriente S.A.', business_name: 'Empresa Regional de Servicio de Electricidad del Oriente S.A.', document_number: '20103795631' }])
LocationOwner.create([{ name: 'Epic Development SAC', business_name: 'Epic Development SAC', document_number: '20517326004' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios C�rpac SA', business_name: 'Estaci�n de Servicios C�rpac SA', document_number: '�20298569311' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios Kio', business_name: 'Estaci�n de Servicios Kio', document_number: '10199198888' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios La Marina SAC', business_name: 'Estaci�n de Servicios La Marina SAC', document_number: '20538585204' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios Lauros SAC', business_name: 'Estaci�n de Servicios Lauros SAC', document_number: '20526093641' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios San Jos� SAC', business_name: 'Estaci�n de Servicios San Jos� SAC', document_number: '20175642341' }])
LocationOwner.create([{ name: 'Estaci�n de Servicios San Roque SAC', business_name: 'Estaci�n de Servicios San Roque SAC', document_number: '20479898091' }])
LocationOwner.create([{ name: 'Estaci�n Santa Margherita SAC', business_name: 'Estaci�n Santa Margherita SAC', document_number: '20508832134' }])
LocationOwner.create([{ name: 'EXCLUSIVE MARKETS SAC', business_name: 'EXCLUSIVE MARKETS SAC', document_number: '20546081878' }])
LocationOwner.create([{ name: 'Explorium Sociedad An�nima Cerrada Explorium S.A.C.', business_name: 'Explorium Sociedad An�nima Cerrada Explorium S.A.C.', document_number: '20514303283' }])
LocationOwner.create([{ name: 'Expreso Molina Uni�n EIRL', business_name: 'Expreso Molina Uni�n EIRL', document_number: '20120550137' }])
LocationOwner.create([{ name: 'Farma San Bartolom� SAC', business_name: 'Farma San Bartolom� SAC', document_number: '20512235787' }])
LocationOwner.create([{ name: 'Farmacia Sandoval SAC', business_name: 'Farmacia Sandoval SAC', document_number: '20384482261' }])
LocationOwner.create([{ name: 'Farmacia Universal SAC', business_name: 'Farmacia Universal SAC', document_number: '20100025168' }])
LocationOwner.create([{ name: 'FARMADESA SRL', business_name: 'FARMADESA SRL', document_number: '20458743038' }])
LocationOwner.create([{ name: 'Farmindustria SA', business_name: 'Farmindustria SA', document_number: '20262996329' }])
LocationOwner.create([{ name: 'Fashion Center SA', business_name: 'Fashion Center SA', document_number: '20512076379' }])
LocationOwner.create([{ name: 'Fenper SA', business_name: 'Fenper SA', document_number: '20126341459' }])
LocationOwner.create([{ name: 'Fito Pan SRL', business_name: 'Fito Pan SRL', document_number: '20354619734' }])
LocationOwner.create([{ name: 'Gaming and Services SA', business_name: 'Gaming and Services SA', document_number: '20305556756' }])
LocationOwner.create([{ name: 'Gaspetroleo SAC', business_name: 'Gaspetroleo SAC', document_number: '20513379138' }])
LocationOwner.create([{ name: 'Gladis Victoria Lodtmann', business_name: 'Gladis Victoria Lodtmann', document_number: '10071563567' }])
LocationOwner.create([{ name: 'GMV  SA', business_name: 'GMV  SA', document_number: '20493040643' }])
LocationOwner.create([{ name: 'Golden Gaming SA', business_name: 'Golden Gaming SA', document_number: '20145118493' }])
LocationOwner.create([{ name: 'Golden Investment SA', business_name: 'Golden Investment SA', document_number: '20346662612' }])
LocationOwner.create([{ name: 'Gran Hotel El Golf Trujillo SA', business_name: 'Gran Hotel El Golf Trujillo SA', document_number: '20274361531' }])
LocationOwner.create([{ name: 'Great Retail SAC', business_name: 'Great Retail SAC', document_number: '20563529378' }])
LocationOwner.create([{ name: 'Grifo Santo Domingo de Guzm�n SRLTDA', business_name: 'Grifo Santo Domingo de Guzm�n SRLTDA', document_number: '20138645607' }])
LocationOwner.create([{ name: 'Grifos Espinoza SA', business_name: 'Grifos Espinoza SA', document_number: '20100111838' }])
LocationOwner.create([{ name: 'Grifosa SAC', business_name: 'Grifosa SAC', document_number: '20100032458' }])
LocationOwner.create([{ name: 'Heinz Glas Per� ', business_name: 'Heinz Glas Per� ', document_number: '20513640316' }])
LocationOwner.create([{ name: 'Hersil SA Laboratorios Industriales Farmac�uticos', business_name: 'Hersil SA Laboratorios Industriales Farmac�uticos', document_number: '20100060150' }])
LocationOwner.create([{ name: 'Hide SA', business_name: 'Hide SA', document_number: '20502138899' }])
LocationOwner.create([{ name: 'Hipermercados Metro S.A.', business_name: 'Hipermercados Metro S.A.', document_number: '20109072177' }])
LocationOwner.create([{ name: 'Hipermercados Tottus SA', business_name: 'Hipermercados Tottus SA', document_number: '20508565934' }])
LocationOwner.create([{ name: 'Home Centers Peruanos S.A.', business_name: 'Home Centers Peruanos S.A.', document_number: '20536557858' }])
LocationOwner.create([{ name: 'Hospedaje Tur�stico San Blas', business_name: 'Hospedaje Tur�stico San Blas', document_number: '20527672962' }])
LocationOwner.create([{ name: 'Hospital Municipal Los Olivos', business_name: 'Hospital Municipal Los Olivos', document_number: '20514772194' }])
LocationOwner.create([{ name: 'Hotelera Costa del Pacífico SA', business_name: 'Hotelera Costa del Pacífico SA', document_number: '20297885538' }])
LocationOwner.create([{ name: 'Hoteles Sheraton del Perú SA', business_name: 'Hoteles Sheraton del Perú SA', document_number: '20100032610' }])
LocationOwner.create([{ name: 'Ica Market Per� SAC', business_name: 'Ica Market Per� SAC', document_number: '20452223652' }])
LocationOwner.create([{ name: 'Importaciones Exportaciones San Luis SA', business_name: 'Importaciones Exportaciones San Luis SA', document_number: '20117813143' }])
LocationOwner.create([{ name: 'Importaciones Hiraoka SAC', business_name: 'Importaciones Hiraoka SAC', document_number: '20100016681' }])
LocationOwner.create([{ name: 'Indejema SA ', business_name: 'Indejema SA ', document_number: '20336778981' }])
LocationOwner.create([{ name: 'Inmobiliaria Banacot SAC', business_name: 'Inmobiliaria Banacot SAC', document_number: '20506324310' }])
LocationOwner.create([{ name: 'INMOBILIARIA EBURNS S.A.C.', business_name: 'INMOBILIARIA EBURNS S.A.C.', document_number: '20548925861' }])
LocationOwner.create([{ name: 'Inmobiliaria El Quinde SAC', business_name: 'Inmobiliaria El Quinde SAC', document_number: '20512817999' }])
LocationOwner.create([{ name: 'Inmobiliaria Viera SAC', business_name: 'Inmobiliaria Viera SAC', document_number: '20515318845' }])
LocationOwner.create([{ name: 'Inmobiliaria y Servicios Masaris SAC', business_name: 'Inmobiliaria y Servicios Masaris SAC', document_number: '20484327948' }])
LocationOwner.create([{ name: 'Inmuebles Panamericana SA', business_name: 'Inmuebles Panamericana SA', document_number: '20423264617' }])
LocationOwner.create([{ name: 'Instituto Peruano de Acci�n Empresarial', business_name: 'Instituto Peruano de Acci�n Empresarial', document_number: '20137254205' }])
LocationOwner.create([{ name: 'Instituto Peruano del Deporte', business_name: 'Instituto Peruano del Deporte', document_number: '20135897044' }])
LocationOwner.create([{ name: 'Interproperties Per�', business_name: 'Interproperties Per�', document_number: '20384537007' }])
LocationOwner.create([{ name: 'Interseguro Compa��a de Seguros de Vida SA', business_name: 'Interseguro Compa��a de Seguros de Vida SA', document_number: '20382748566' }])
LocationOwner.create([{ name: 'Inversiones Balora SAC', business_name: 'Inversiones Balora SAC', document_number: '20495648215' }])
LocationOwner.create([{ name: 'Inversiones Bulgaria SA', business_name: 'Inversiones Bulgaria SA', document_number: '20341237999' }])
LocationOwner.create([{ name: 'Inversiones en Turismo SA ', business_name: 'Inversiones en Turismo SA ', document_number: '20104347691' }])
LocationOwner.create([{ name: 'Inversiones Fortunia S.A.', business_name: 'Inversiones Fortunia S.A.', document_number: '20110614439' }])
LocationOwner.create([{ name: 'Inversiones Hemaje EIRL', business_name: 'Inversiones Hemaje EIRL', document_number: '20506572135' }])
LocationOwner.create([{ name: 'Inversiones Hobby SAC', business_name: 'Inversiones Hobby SAC', document_number: '20113122847' }])
LocationOwner.create([{ name: 'INVERSIONES HOSPERU SRL', business_name: 'INVERSIONES HOSPERU SRL', document_number: '20537242648' }])
LocationOwner.create([{ name: 'Inversiones Julio & Olenka SAC', business_name: 'Inversiones Julio & Olenka SAC', document_number: '20338694360' }])
LocationOwner.create([{ name: 'Inversiones Kincorp SAC', business_name: 'Inversiones Kincorp SAC', document_number: '20506657394' }])
LocationOwner.create([{ name: 'Inversiones La S�tima de Gamarra SAC', business_name: 'Inversiones La S�tima de Gamarra SAC', document_number: '20372465736' }])
LocationOwner.create([{ name: 'Inversiones M y S SAC', business_name: 'Inversiones M y S SAC', document_number: '20117161138' }])
LocationOwner.create([{ name: 'INVERSIONES MAJE S.A.', business_name: 'INVERSIONES MAJE S.A.', document_number: '20517855929' }])
LocationOwner.create([{ name: 'Inversiones Manuel Tenorio SA', business_name: 'Inversiones Manuel Tenorio SA', document_number: '20407236255' }])
LocationOwner.create([{ name: 'Inversiones MG Huarochiri S.A.C.', business_name: 'Inversiones MG Huarochiri S.A.C.', document_number: '20548562377' }])
LocationOwner.create([{ name: 'Inversiones Thewaly S.A.C.', business_name: 'Inversiones Thewaly S.A.C.', document_number: '20544357388' }])
LocationOwner.create([{ name: 'Inversiones TPC SAC', business_name: 'Inversiones TPC SAC', document_number: '20513649291' }])
LocationOwner.create([{ name: 'Inversiones Y Servicios Inmobiliarios SAC', business_name: 'Inversiones Y Servicios Inmobiliarios SAC', document_number: '20544314816' }])
LocationOwner.create([{ name: 'Investur Cusco SAC', business_name: 'Investur Cusco SAC', document_number: '20522383156' }])
LocationOwner.create([{ name: 'IQF del Perú SA', business_name: 'IQF del Perú SA', document_number: '20100032709' }])
LocationOwner.create([{ name: 'Jhodaal SAC', business_name: 'Jhodaal SAC', document_number: '20506994986' }])
LocationOwner.create([{ name: 'Jorge Iv�n Gonz�les Obando', business_name: 'Jorge Iv�n Gonz�les Obando', document_number: '23814133000' }])
LocationOwner.create([{ name: 'Junta de Propietarios de la Galer�a Mercado Central', business_name: 'Junta de Propietarios de la Galer�a Mercado Central', document_number: '20491956560' }])
LocationOwner.create([{ name: 'Junta de Propietarios del C.C. Alameda del Calzado', business_name: 'Junta de Propietarios del C.C. Alameda del Calzado', document_number: '20481293589' }])
LocationOwner.create([{ name: 'Junta de Propietarios del Centro Comercial Caminos del Inca', business_name: 'Junta de Propietarios del Centro Comercial Caminos del Inca', document_number: '20161757226' }])
LocationOwner.create([{ name: 'Junta de Propietarios del Centro Comercial La Feria Polvos Rosados de Higuereta', business_name: 'Junta de Propietarios del Centro Comercial La Feria Polvos Rosados de Higuereta', document_number: '20426836981' }])
LocationOwner.create([{ name: 'JUNTA DE PROPIETARIOS DEL EDIFICIO SAN SEBASTIAN', business_name: 'JUNTA DE PROPIETARIOS DEL EDIFICIO SAN SEBASTIAN', document_number: '20460428913' }])
LocationOwner.create([{ name: 'Junta de Propietarios Food Market Casuarinas', business_name: 'Junta de Propietarios Food Market Casuarinas', document_number: '20467120485' }])
LocationOwner.create([{ name: 'Junta Gral. de Propietarios Mercado Modelo Covida', business_name: 'Junta Gral. de Propietarios Mercado Modelo Covida', document_number: '20148093505' }])
LocationOwner.create([{ name: 'Kata Alpaca SAC', business_name: 'Kata Alpaca SAC', document_number: '20602909183' }])
LocationOwner.create([{ name: 'La Asociación Gran Mercado del Cono Norte Zarumilla Caquet�', business_name: 'La Asociación Gran Mercado del Cono Norte Zarumilla Caquet�', document_number: '20333042852' }])
LocationOwner.create([{ name: 'LA ESQUINA DE LA PLANICIE S.A.C.', business_name: 'LA ESQUINA DE LA PLANICIE S.A.C.', document_number: '20492926869' }])
LocationOwner.create([{ name: 'Lima Airport Partners SRL', business_name: 'Lima Airport Partners SRL', document_number: '20501577252' }])
LocationOwner.create([{ name: 'Los Alamos Machines Investments SA', business_name: 'Los Alamos Machines Investments SA', document_number: '20388082144' }])
LocationOwner.create([{ name: 'Luis Felipe Abusada Heresi y Juan Carlos Abusada Heresi', business_name: 'Luis Felipe Abusada Heresi y Juan Carlos Abusada Heresi', document_number: '29593388000' }])
LocationOwner.create([{ name: 'Magic Center SCRL', business_name: 'Magic Center SCRL', document_number: '20321642854' }])
LocationOwner.create([{ name: 'MAKRO SUPERMAYORISTA S.A.', business_name: 'MAKRO SUPERMAYORISTA S.A.', document_number: '20492092313' }])
LocationOwner.create([{ name: 'Malls Per� SA', business_name: 'Malls Per� SA', document_number: '20266409461' }])
LocationOwner.create([{ name: 'Manuel Igreda & Julio R�os SRL', business_name: 'Manuel Igreda & Julio R�os SRL', document_number: '20101127614' }])
LocationOwner.create([{ name: 'Mar�a Elena Esp�ritu Li�an', business_name: 'Mar�a Elena Esp�ritu Li�an', document_number: '10413989944' }])
LocationOwner.create([{ name: 'Mar�a Elena Quispe Medina', business_name: 'Mar�a Elena Quispe Medina', document_number: '10255727422' }])
LocationOwner.create([{ name: 'Marina de Guerra del Perú', business_name: 'Marina de Guerra del Perú', document_number: '20153408191' }])
LocationOwner.create([{ name: 'Marsano Palace Towers SA', business_name: 'Marsano Palace Towers SA', document_number: '20468366186' }])
LocationOwner.create([{ name: 'Martha Perez Medina', business_name: 'Martha Perez Medina', document_number: '40785508000' }])
LocationOwner.create([{ name: 'Maxus SAC', business_name: 'Maxus SAC', document_number: '20514053236' }])
LocationOwner.create([{ name: 'Mayorsa SA', business_name: 'Mayorsa SA', document_number: '20108730294' }])
LocationOwner.create([{ name: 'M�dicos Asociados Cusco S.A.', business_name: 'M�dicos Asociados Cusco S.A.', document_number: '20527956057' }])
LocationOwner.create([{ name: 'Memor�a JMC SAC', business_name: 'Memor�a JMC SAC', document_number: '20507409190' }])
LocationOwner.create([{ name: 'Merino Vereau César Wellington', business_name: 'Merino Vereau César Wellington', document_number: '10180713897' }])
LocationOwner.create([{ name: 'Mes�as David Alzamora Manrique', business_name: 'Mes�as David Alzamora Manrique', document_number: '86761790000' }])
LocationOwner.create([{ name: 'MIFARMA S.A.C.', business_name: 'MIFARMA S.A.C.', document_number: '20512002090' }])
LocationOwner.create([{ name: 'Minimarket Marlon SAC', business_name: 'Minimarket Marlon SAC', document_number: '20525214088' }])
LocationOwner.create([{ name: 'Ministerio de Relaciones Exteriores', business_name: 'Ministerio de Relaciones Exteriores', document_number: '20131380101' }])
LocationOwner.create([{ name: 'Ministerio de Salud', business_name: 'Ministerio de Salud', document_number: '20131373237' }])
LocationOwner.create([{ name: 'MIXERCON S.A.', business_name: 'MIXERCON S.A.', document_number: '20380289360' }])
LocationOwner.create([{ name: 'Monasterio de la Concepción', business_name: 'Monasterio de la Concepción', document_number: '20171649294' }])
LocationOwner.create([{ name: 'MRBT SAC', business_name: 'MRBT SAC', document_number: '20504900259' }])
LocationOwner.create([{ name: 'Multimercados Zonales SA', business_name: 'Multimercados Zonales SA', document_number: '20421526258' }])
LocationOwner.create([{ name: 'Mundo Electr�nico SAC', business_name: 'Mundo Electr�nico SAC', document_number: '20463145734' }])
LocationOwner.create([{ name: 'Municipalidad de San Borja', business_name: 'Municipalidad de San Borja', document_number: '20131373741' }])
LocationOwner.create([{ name: 'Municipalidad Distrital de Paracas', business_name: 'Municipalidad Distrital de Paracas', document_number: '20162427301' }])
LocationOwner.create([{ name: 'Municipalidad Distrital de Santiago', business_name: 'Municipalidad Distrital de Santiago', document_number: '20147711159' }])
LocationOwner.create([{ name: 'Municipalidad Provincial de Arequipa', business_name: 'Municipalidad Provincial de Arequipa', document_number: '20154489895' }])
LocationOwner.create([{ name: 'Municipalidad Provincial de Mariscal Nieto', business_name: 'Municipalidad Provincial de Mariscal Nieto', document_number: '29594465000' }])
LocationOwner.create([{ name: 'Municipalidad Provincial de Tacna', business_name: 'Municipalidad Provincial de Tacna', document_number: '20147797100' }])
LocationOwner.create([{ name: 'Municipalidad Provincial del Cusco', business_name: 'Municipalidad Provincial del Cusco', document_number: '20177217043' }])
LocationOwner.create([{ name: 'MZ - Inmobiliaria y Desarrolladora SA', business_name: 'MZ - Inmobiliaria y Desarrolladora SA', document_number: '20524436796' }])
LocationOwner.create([{ name: 'Negociaciones e Inversiones Doral SAC', business_name: 'Negociaciones e Inversiones Doral SAC', document_number: '20531521987' }])
LocationOwner.create([{ name: 'Nessus Hoteles Per� S.A.', business_name: 'Nessus Hoteles Per� S.A.', document_number: '20505670443' }])
LocationOwner.create([{ name: 'New Port Capital SAC', business_name: 'New Port Capital SAC', document_number: '20513020792' }])
LocationOwner.create([{ name: 'NG Restaurants SA', business_name: 'NG Restaurants SA', document_number: '20545801770' }])
LocationOwner.create([{ name: 'Organizaci�n Futuro SAC ', business_name: 'Organizaci�n Futuro SAC ', document_number: '20177941591' }])
LocationOwner.create([{ name: 'Ormachea Vda de Valer Olimpia Luisa', business_name: 'Ormachea Vda de Valer Olimpia Luisa', document_number: '10238146050' }])
LocationOwner.create([{ name: 'Otifarma SAC', business_name: 'Otifarma SAC', document_number: '20514374032' }])
LocationOwner.create([{ name: 'Pacífico Inversi�n y Desarrollo SAC', business_name: 'Pacífico Inversi�n y Desarrollo SAC', document_number: '20525468349' }])
LocationOwner.create([{ name: 'Palacio Real SA', business_name: 'Palacio Real SA', document_number: '20190016103' }])
LocationOwner.create([{ name: 'Parque Lambramani SAC', business_name: 'Parque Lambramani SAC', document_number: '20523173716' }])
LocationOwner.create([{ name: 'Patio Gastronomico SAC', business_name: 'Patio Gastronomico SAC', document_number: '20603867689' }])
LocationOwner.create([{ name: 'Patrimonio en Fideicomiso DS N� 093-2002-EF Interproperties Per�', business_name: 'Patrimonio en Fideicomiso DS N� 093-2002-EF Interproperties Per�', document_number: '20519398169' }])
LocationOwner.create([{ name: 'Patronato del Parque de las Leyendas - Felipe Benavides Barreda', business_name: 'Patronato del Parque de las Leyendas - Felipe Benavides Barreda', document_number: '20125645039' }])
LocationOwner.create([{ name: 'Pedro Huachin Soto', business_name: 'Pedro Huachin Soto', document_number: '10103892665' }])
LocationOwner.create([{ name: 'Pentarama SA', business_name: 'Pentarama SA', document_number: '20510360932' }])
LocationOwner.create([{ name: 'Peruana de Estaciones de Servicios SAC ', business_name: 'Peruana de Estaciones de Servicios SAC ', document_number: '20330033313' }])
LocationOwner.create([{ name: 'Peruana de Gas Natural SAC', business_name: 'Peruana de Gas Natural SAC', document_number: '20511995028' }])
LocationOwner.create([{ name: 'Peruplast SA', business_name: 'Peruplast SA', document_number: '20100175569' }])
LocationOwner.create([{ name: 'Petr�leos del Perú Petroper� SA', business_name: 'Petr�leos del Perú Petroper� SA', document_number: '20100128218' }])
LocationOwner.create([{ name: 'Petrosur SAC', business_name: 'Petrosur SAC', document_number: '20291490388' }])
LocationOwner.create([{ name: 'Plaza Lima Norte SAC', business_name: 'Plaza Lima Norte SAC', document_number: '20514020907' }])
LocationOwner.create([{ name: 'Poder Judicial', business_name: 'Poder Judicial', document_number: '20159981216' }])
LocationOwner.create([{ name: 'Pontificia Universidad Cat�lica del Perú', business_name: 'Pontificia Universidad Cat�lica del Perú', document_number: '20155945860' }])
LocationOwner.create([{ name: 'Portal Los Vi�edos SRL', business_name: 'Portal Los Vi�edos SRL', document_number: '20520476335' }])
LocationOwner.create([{ name: 'Pricewaterhouse Coopers Sociedad Civil RLTDA', business_name: 'Pricewaterhouse Coopers Sociedad Civil RLTDA', document_number: '20101071562' }])
LocationOwner.create([{ name: 'Promotora Asistencial SAC', business_name: 'Promotora Asistencial SAC', document_number: '20101098681' }])
LocationOwner.create([{ name: 'Promotora e Inversiones Palace SAC', business_name: 'Promotora e Inversiones Palace SAC', document_number: '20101140041' }])
LocationOwner.create([{ name: 'Promotora El Dorado SAC', business_name: 'Promotora El Dorado SAC', document_number: '20254684229' }])
LocationOwner.create([{ name: 'Propiedades Inmobiliarias SAC', business_name: 'Propiedades Inmobiliarias SAC', document_number: '20336565643' }])
LocationOwner.create([{ name: 'QUIMICA SUIZA S.A.', business_name: 'QUIMICA SUIZA S.A.', document_number: '20100085225' }])
LocationOwner.create([{ name: 'RAFAEL JARA CARLOS MANUEL', business_name: 'RAFAEL JARA CARLOS MANUEL', document_number: '10441826732' }])
LocationOwner.create([{ name: 'Recreativos Fargo SAC', business_name: 'Recreativos Fargo SAC', document_number: '20526938535' }])
LocationOwner.create([{ name: 'Recreativos Slots del Pacífico SAC', business_name: 'Recreativos Slots del Pacífico SAC', document_number: '20486352613' }])
LocationOwner.create([{ name: 'Repsol Comercial SAC', business_name: 'Repsol Comercial SAC', document_number: '20503840121' }])
LocationOwner.create([{ name: 'Reybass SAC', business_name: 'Reybass SAC', document_number: '20511968136' }])
LocationOwner.create([{ name: 'Riad Antonio Mattar Abusada', business_name: 'Riad Antonio Mattar Abusada', document_number: '10415210391' }])
LocationOwner.create([{ name: 'Rico Pollo S.A.C', business_name: 'Rico Pollo S.A.C', document_number: '20121685435' }])
LocationOwner.create([{ name: 'Rocina Luisa Abanto Paredes', business_name: 'Rocina Luisa Abanto Paredes', document_number: '20511803218' }])
LocationOwner.create([{ name: 'Rodr�guez de Benavides Dora', business_name: 'Rodr�guez de Benavides Dora', document_number: '25315841000' }])
LocationOwner.create([{ name: 'Rojas Market EIRL', business_name: 'Rojas Market EIRL', document_number: '20452258103' }])
LocationOwner.create([{ name: 'Royal Entertainment SAC', business_name: 'Royal Entertainment SAC', document_number: '20144926740' }])
LocationOwner.create([{ name: 'S.Rodr�guez Banda SAC ', business_name: 'S.Rodr�guez Banda SAC ', document_number: '20504126367' }])
LocationOwner.create([{ name: 'Sajo Market SAC', business_name: 'Sajo Market SAC', document_number: '20518253906' }])
LocationOwner.create([{ name: 'Salgrisa SAC', business_name: 'Salgrisa SAC', document_number: '20141202112' }])
LocationOwner.create([{ name: 'Savia Per� S.A.', business_name: 'Savia Per� S.A.', document_number: '20203058781' }])
LocationOwner.create([{ name: 'SB Trading SRL', business_name: 'SB Trading SRL', document_number: '20101567428' }])
LocationOwner.create([{ name: 'Seafrost SAC', business_name: 'Seafrost SAC', document_number: '20356922311' }])
LocationOwner.create([{ name: 'Sedapar SA', business_name: 'Sedapar SA', document_number: '20100211034' }])
LocationOwner.create([{ name: 'Seguro Social de Salud', business_name: 'Seguro Social de Salud', document_number: '20131257750' }])
LocationOwner.create([{ name: 'Sergio Guevara Valdivia', business_name: 'Sergio Guevara Valdivia', document_number: '10253106676' }])
LocationOwner.create([{ name: 'Servicio de Agua Potable y Alcantarillado de Lima - SEDAPAL', business_name: 'Servicio de Agua Potable y Alcantarillado de Lima - SEDAPAL', document_number: '20100152356' }])
LocationOwner.create([{ name: 'SERVICIO NACIONAL DE ADIESTRAMIENTO EN TRABAJO INDUSTRIAL', business_name: 'SERVICIO NACIONAL DE ADIESTRAMIENTO EN TRABAJO INDUSTRIAL', document_number: '20131376503' }])
LocationOwner.create([{ name: 'Servicio Social del Director y Supervisor', business_name: 'Servicio Social del Director y Supervisor', document_number: '20100859778' }])
LocationOwner.create([{ name: 'Sierra Machines SAC', business_name: 'Sierra Machines SAC', document_number: '20486229927' }])
LocationOwner.create([{ name: 'Silverbell SAC', business_name: 'Silverbell SAC', document_number: '20510153040' }])
LocationOwner.create([{ name: 'Simiona de la Cruz Moreno', business_name: 'Simiona de la Cruz Moreno', document_number: '71466660000' }])
LocationOwner.create([{ name: 'Sonia Nelly Bobadilla Alfaro', business_name: 'Sonia Nelly Bobadilla Alfaro', document_number: '10087478390' }])
LocationOwner.create([{ name: 'STRIP CENTERS DEL PERU S.A.', business_name: 'STRIP CENTERS DEL PERU S.A.', document_number: '20550880041' }])
LocationOwner.create([{ name: 'Sun Inversiones SAC', business_name: 'Sun Inversiones SAC', document_number: '20486229684' }])
LocationOwner.create([{ name: 'Superintendencia Nacional de Administraci�n Tributaria', business_name: 'Superintendencia Nacional de Administraci�n Tributaria', document_number: '20131312955' }])
LocationOwner.create([{ name: 'Supermercado Candy SAC', business_name: 'Supermercado Candy SAC', document_number: '20516261090' }])
LocationOwner.create([{ name: 'Supermercados Peruanos S.A.', business_name: 'Supermercados Peruanos S.A.', document_number: '20100070970' }])
LocationOwner.create([{ name: 'Svenza Zona Franca SRL', business_name: 'Svenza Zona Franca SRL', document_number: '20164486720' }])
LocationOwner.create([{ name: 'Tapia Zunilda Genoveva', business_name: 'Tapia Zunilda Genoveva', document_number: '10214396730' }])
LocationOwner.create([{ name: 'Terminal Terrestre de Huancayo SA', business_name: 'Terminal Terrestre de Huancayo SA', document_number: '20508404680' }])
LocationOwner.create([{ name: 'Terminal Terrestre Ica SA', business_name: 'Terminal Terrestre Ica SA', document_number: '20144298161' }])
LocationOwner.create([{ name: 'Terrapuerto Plaza Wari SAC', business_name: 'Terrapuerto Plaza Wari SAC', document_number: '20536862227' }])
LocationOwner.create([{ name: 'Texas Gaming Corporation S.A.C.', business_name: 'Texas Gaming Corporation S.A.C.', document_number: '20511532516' }])
LocationOwner.create([{ name: 'Thunderbird Fiesta Casino-Benavides SA', business_name: 'Thunderbird Fiesta Casino-Benavides SA', document_number: '20516403811' }])
LocationOwner.create([{ name: 'TIENDAS Y COMERCIOS del Perú S.A.C.', business_name: 'TIENDAS Y COMERCIOS del Perú S.A.C.', document_number: '20601880891' }])
LocationOwner.create([{ name: 'Tierra Sur Entretenimientos S.R.L.', business_name: 'Tierra Sur Entretenimientos S.R.L.', document_number: '20387775219' }])
LocationOwner.create([{ name: 'TM Gesti�n Inmobiliaria SAC', business_name: 'TM Gesti�n Inmobiliaria SAC', document_number: '20511038821' }])
LocationOwner.create([{ name: 'Total Artefactos S.A.', business_name: 'Total Artefactos S.A.', document_number: '20331429601' }])
LocationOwner.create([{ name: 'Tourist Entretenimientos SAC', business_name: 'Tourist Entretenimientos SAC', document_number: '20527033528' }])
LocationOwner.create([{ name: 'Transportes Cruz del Sur SAC', business_name: 'Transportes Cruz del Sur SAC', document_number: '20100227461' }])
LocationOwner.create([{ name: 'Transportes CánepaSA', business_name: 'Transportes CánepaSA', document_number: '20438933272' }])
LocationOwner.create([{ name: 'Trastiendas Integradas SAC', business_name: 'Trastiendas Integradas SAC', document_number: '20507884823' }])
LocationOwner.create([{ name: 'Tres Palmeras SA', business_name: 'Tres Palmeras SA', document_number: '20208388500' }])
LocationOwner.create([{ name: 'Turismo Costa del Sol ', business_name: 'Turismo Costa del Sol ', document_number: '20356883749' }])
LocationOwner.create([{ name: 'UCIK Asociación Civil ', business_name: 'UCIK Asociación Civil ', document_number: '20518407555' }])
LocationOwner.create([{ name: 'UNIMAQ S.A.', business_name: 'UNIMAQ S.A.', document_number: '20100027021' }])
LocationOwner.create([{ name: 'Universidad Andina del Cuzco', business_name: 'Universidad Andina del Cuzco', document_number: '20177395227' }])
LocationOwner.create([{ name: 'UNIVERSIDAD César VALLEJO S.A.C', business_name: 'UNIVERSIDAD César VALLEJO S.A.C', document_number: '20164113532' }])
LocationOwner.create([{ name: 'UNIVERSIDAD CIENT�FICA DEL SUR S.A.C', business_name: 'UNIVERSIDAD CIENT�FICA DEL SUR S.A.C', document_number: '20421239275' }])
LocationOwner.create([{ name: 'Universidad de Lima', business_name: 'Universidad de Lima', document_number: '20107798049' }])
LocationOwner.create([{ name: 'Universidad de San Martín de Porres', business_name: 'Universidad de San Martín de Porres', document_number: '20138149022' }])
LocationOwner.create([{ name: 'Universidad del Pacífico', business_name: 'Universidad del Pacífico', document_number: '20109705129' }])
LocationOwner.create([{ name: 'Universidad Nacional de Ingenier�a', business_name: 'Universidad Nacional de Ingenier�a', document_number: '20169004359' }])
LocationOwner.create([{ name: 'Universidad Nacional de Piura', business_name: 'Universidad Nacional de Piura', document_number: '20172606777' }])
LocationOwner.create([{ name: 'UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS', business_name: 'UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS', document_number: '20211614545' }])
LocationOwner.create([{ name: 'Universidad Privada del Norte SAC', business_name: 'Universidad Privada del Norte SAC', document_number: '20215276024' }])
LocationOwner.create([{ name: 'Universidad Tecnol�gica del Perú', business_name: 'Universidad Tecnol�gica del Perú', document_number: '20462509236' }])
LocationOwner.create([{ name: 'Vesalio SA', business_name: 'Vesalio SA', document_number: '20100178401' }])
LocationOwner.create([{ name: 'Vimape SAC', business_name: 'Vimape SAC', document_number: '20440328726' }])
LocationOwner.create([{ name: 'Weber SAC', business_name: 'Weber SAC', document_number: '20514052779' }])
LocationOwner.create([{ name: 'Ysabel Canchanya Porras', business_name: 'Ysabel Canchanya Porras', document_number: '98486900003' }])
LocationOwner.create([{ name: 'Ysabel Quispe de Carignano', business_name: 'Ysabel Quispe de Carignano', document_number: '78960350000' }])

puts "11_LocationOwner_seeds done at: " + Time.new.to_s
